package com.joebywan.daybook.ui.play

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.WindowInsets
import androidx.compose.foundation.layout.safeDrawing
import androidx.compose.foundation.layout.windowInsetsPadding
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.automirrored.filled.Undo
import androidx.compose.material.icons.filled.AutoAwesome
import androidx.compose.material.icons.automirrored.filled.HelpOutline
import androidx.compose.material.icons.filled.Refresh
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.produceState
import androidx.compose.runtime.remember
import androidx.compose.runtime.saveable.Saver
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.runtime.snapshotFlow
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.unit.dp
import com.joebywan.daybook.core.Difficulty
import com.joebywan.daybook.core.PuzzleType
import com.joebywan.daybook.data.SavedGame
import com.joebywan.daybook.puzzles.PuzzleState
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.NonCancellable
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.collectLatest
import kotlinx.coroutines.withContext
import java.time.LocalDate
import java.time.format.DateTimeFormatter

private val PlayDate = DateTimeFormatter.ofPattern("d MMM yyyy")

/** Long enough that holding down a Sudoku digit is one write rather than a dozen. */
private const val SAVE_DEBOUNCE_MS = 500L

/**
 * Rotation goes through the same JSON as the on-disk store: one format to get right, and a board
 * that survives a turn of the phone is proof the stored one will load too.
 */
private val SavedGameSaver = Saver<SavedGame, String>(
    save = { it.encode() },
    restore = SavedGame::decode,
)

@Composable
fun PlayScreen(
    puzzle: PuzzleType,
    difficulty: Difficulty,
    day: LocalDate?,
    seed: Long,
    restore: suspend () -> SavedGame?,
    persist: suspend (SavedGame?) -> Unit,
    onSolved: (seconds: Int, hints: Int) -> Unit,
    onAgain: () -> Unit,
    onBack: () -> Unit,
) {
    // The harder boards take hundreds of milliseconds to generate, which would freeze the frame if
    // it happened during composition. It runs off the main thread and the screen waits for it.
    val generated by produceState<PuzzleState?>(null, puzzle.id, seed, difficulty) {
        value = withContext(Dispatchers.Default) { puzzle.generate(seed, difficulty) }
    }

    val ready = generated
    if (ready == null) {
        DealingBoard(puzzle, onBack)
    } else {
        PlayBoard(puzzle, difficulty, day, ready, restore, persist, onSolved, onAgain, onBack)
    }
}

@Composable
private fun DealingBoard(puzzle: PuzzleType, onBack: () -> Unit) {
    val scheme = MaterialTheme.colorScheme
    Column(
        Modifier
            .fillMaxSize()
            .background(scheme.background)
            .windowInsetsPadding(WindowInsets.safeDrawing)
    ) {
        Row(
            Modifier.fillMaxWidth().padding(start = 8.dp, end = 8.dp, top = 8.dp),
            verticalAlignment = Alignment.CenterVertically,
        ) {
            IconCircle(Icons.AutoMirrored.Filled.ArrowBack, "Back", onBack)
        }
        Box(Modifier.weight(1f), contentAlignment = Alignment.Center) {
            Text(
                "Setting out ${puzzle.displayName}...",
                style = MaterialTheme.typography.bodyMedium,
                color = scheme.onSurfaceVariant,
            )
        }
    }
}

@Composable
private fun PlayBoard(
    puzzle: PuzzleType,
    difficulty: Difficulty,
    day: LocalDate?,
    initial: PuzzleState,
    restore: suspend () -> SavedGame?,
    persist: suspend (SavedGame?) -> Unit,
    onSolved: (seconds: Int, hints: Int) -> Unit,
    onAgain: () -> Unit,
    onBack: () -> Unit,
) {
    val scheme = MaterialTheme.colorScheme

    val pristine = remember(initial) { SavedGame(initial) }
    var game by rememberSaveable(initial, stateSaver = SavedGameSaver) { mutableStateOf(pristine) }
    // Saved alongside the game: without it, rotating a finished board would record the win twice.
    var recorded by rememberSaveable(initial) { mutableStateOf(false) }
    // Set as soon as the store has been asked, and itself saved, so the answer that arrived before
    // the rotation is not thrown away by a second lookup afterwards.
    var consulted by rememberSaveable(initial) { mutableStateOf(false) }
    var showRules by remember { mutableStateOf(false) }

    val state = game.state
    val seconds = game.seconds

    // Reads `game` rather than the values unpacked above: this runs from effects that outlive the
    // composition that started them, where those locals would be frozen at their first value.
    suspend fun flush() {
        val current = game
        when {
            // A finished board must never come back as "in progress".
            current.state.solved -> persist(null)
            // Opened and never touched. Nothing to record, and nothing of anyone's to clear.
            current == pristine -> Unit
            // Restarted, or only ever selected a cell: no longer a game in progress.
            current.state.moves == 0 -> persist(null)
            else -> persist(current)
        }
    }

    LaunchedEffect(initial) {
        if (consulted) return@LaunchedEffect
        val stored = restore()
        // Reading the store takes a moment; a tap that landed in the meantime outranks it.
        if (stored != null && game == pristine) game = stored
        consulted = true
    }

    LaunchedEffect(initial) {
        while (true) {
            delay(1000)
            if (!game.state.solved) game = game.copy(seconds = game.seconds + 1)
        }
    }

    // Deliberately watches the board and not the clock: ticking the seconds is not progress worth
    // a write, so a game abandoned without touching it keeps the time it had at the last move.
    LaunchedEffect(initial) {
        try {
            snapshotFlow { game.state }.collectLatest {
                delay(SAVE_DEBOUNCE_MS)
                flush()
            }
        } finally {
            // The screen is going away, possibly with the process; the write has to outlive it.
            withContext(NonCancellable) { flush() }
        }
    }

    LaunchedEffect(state.solved) {
        if (state.solved && !recorded) {
            recorded = true
            onSolved(seconds, game.hints)
        }
    }

    // Reads through `game` rather than the unpacked locals so that two taps landing in the same
    // frame stack up properly instead of pushing the same board twice.
    fun push(next: PuzzleState) {
        game = game.copy(state = next, history = game.history + game.state)
    }

    Column(
        Modifier
            .fillMaxSize()
            .background(scheme.background)
            .windowInsetsPadding(WindowInsets.safeDrawing)
    ) {
        Row(
            Modifier.fillMaxWidth().padding(start = 8.dp, end = 8.dp, top = 8.dp, bottom = 6.dp),
            verticalAlignment = Alignment.CenterVertically,
        ) {
            IconCircle(Icons.AutoMirrored.Filled.ArrowBack, "Back", onBack)
            Column(Modifier.weight(1f), horizontalAlignment = Alignment.CenterHorizontally) {
                Text(
                    puzzle.displayName,
                    style = MaterialTheme.typography.titleLarge,
                    color = scheme.onBackground,
                )
                Text(
                    buildString {
                        append(difficulty.label)
                        append(" · ")
                        append(day?.format(PlayDate) ?: "Practice")
                    },
                    style = MaterialTheme.typography.labelLarge,
                    color = scheme.onSurfaceVariant,
                )
            }
            IconCircle(Icons.AutoMirrored.Filled.HelpOutline, "How to play") { showRules = true }
        }

        Text(
            text = "%d:%02d".format(seconds / 60, seconds % 60),
            style = MaterialTheme.typography.titleMedium,
            color = scheme.onSurfaceVariant,
            modifier = Modifier.fillMaxWidth().padding(bottom = 4.dp),
            textAlign = androidx.compose.ui.text.style.TextAlign.Center,
        )

        Box(Modifier.weight(1f), contentAlignment = Alignment.Center) {
            puzzle.Board(
                state = state,
                onState = { next -> push(next) },
                interactive = !state.solved,
            )
        }

        if (state.solved) {
            SolvedBar(
                seconds = seconds,
                hints = game.hints,
                accent = Color(puzzle.accent),
                onAgain = onAgain,
                onBack = onBack,
            )
        } else {
            Row(
                Modifier.fillMaxWidth().padding(horizontal = 18.dp, vertical = 22.dp),
                horizontalArrangement = Arrangement.spacedBy(12.dp),
            ) {
                ToolButton(Icons.AutoMirrored.Filled.Undo, "Undo", Modifier.weight(1f)) {
                    game.history.lastOrNull()?.let {
                        game = game.copy(state = it, history = game.history.dropLast(1))
                    }
                }
                ToolButton(Icons.Default.Refresh, "Restart", Modifier.weight(1f)) {
                    game = game.copy(state = initial, history = emptyList())
                }
                if (puzzle.offersHints) {
                    ToolButton(Icons.Default.AutoAwesome, "Hint", Modifier.weight(1f)) {
                        puzzle.hint(state)?.let {
                            game = game.copy(hints = game.hints + 1)
                            push(it)
                        }
                    }
                }
            }
        }
    }

    if (showRules) {
        AlertDialog(
            onDismissRequest = { showRules = false },
            confirmButton = {
                TextButton(onClick = { showRules = false }) { Text("Got it") }
            },
            title = { Text("How to play ${puzzle.displayName}") },
            text = {
                Column(Modifier.verticalScroll(rememberScrollState())) {
                    puzzle.rules.forEach { rule ->
                        Text("•  $rule", style = MaterialTheme.typography.bodyMedium)
                        Spacer(Modifier.height(8.dp))
                    }
                }
            },
        )
    }
}

@Composable
private fun SolvedBar(
    seconds: Int,
    hints: Int,
    accent: Color,
    onAgain: () -> Unit,
    onBack: () -> Unit,
) {
    val scheme = MaterialTheme.colorScheme
    Column(
        Modifier
            .fillMaxWidth()
            .padding(18.dp)
            .clip(RoundedCornerShape(20.dp))
            .background(accent.copy(alpha = 0.18f))
            .padding(18.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
    ) {
        Text("Solved", style = MaterialTheme.typography.titleLarge, color = accent)
        Text(
            buildString {
                append("%d:%02d".format(seconds / 60, seconds % 60))
                if (hints > 0) append("  ·  $hints hint${if (hints == 1) "" else "s"}")
            },
            style = MaterialTheme.typography.bodyMedium,
            color = scheme.onSurface,
        )
        Spacer(Modifier.height(14.dp))
        Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
            TextButton(onClick = onAgain) { Text("Another") }
            TextButton(onClick = onBack) { Text("Done") }
        }
    }
}

@Composable
private fun IconCircle(icon: ImageVector, label: String, onClick: () -> Unit) {
    val scheme = MaterialTheme.colorScheme
    Box(
        Modifier.size(44.dp).clip(CircleShape).clickable(onClick = onClick),
        contentAlignment = Alignment.Center,
    ) {
        Icon(icon, label, tint = scheme.onSurfaceVariant)
    }
}

@Composable
private fun ToolButton(icon: ImageVector, label: String, modifier: Modifier, onClick: () -> Unit) {
    val scheme = MaterialTheme.colorScheme
    Column(
        modifier
            .clip(RoundedCornerShape(16.dp))
            .background(scheme.surface)
            .clickable(onClick = onClick)
            .padding(vertical = 13.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
    ) {
        Icon(icon, label, tint = scheme.onSurfaceVariant, modifier = Modifier.size(22.dp))
        Spacer(Modifier.height(4.dp))
        Text(label, style = MaterialTheme.typography.labelLarge, color = scheme.onSurfaceVariant)
    }
}
