package com.joebywan.daybook.ui.play

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.automirrored.filled.Undo
import androidx.compose.material.icons.filled.AutoAwesome
import androidx.compose.material.icons.automirrored.filled.HelpOutline
import androidx.compose.material.icons.filled.Refresh
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.produceState
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.unit.dp
import com.joebywan.daybook.core.Difficulty
import com.joebywan.daybook.core.PuzzleState
import com.joebywan.daybook.core.PuzzleType
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.withContext
import java.time.LocalDate
import java.time.format.DateTimeFormatter

private val PlayDate = DateTimeFormatter.ofPattern("d MMM yyyy")

@Composable
fun PlayScreen(
    puzzle: PuzzleType,
    difficulty: Difficulty,
    day: LocalDate?,
    seed: Long,
    onSolved: (seconds: Int, hints: Int) -> Unit,
    onAgain: () -> Unit,
    onBack: () -> Unit,
) {
    // The harder boards take hundreds of milliseconds to generate, which would freeze the frame if
    // it happened during composition. It runs off the main thread and the screen waits for it.
    val generated by produceState<PuzzleState?>(null, puzzle.id, seed, difficulty) {
        value = withContext(Dispatchers.Default) { puzzle.generate(seed, difficulty) }
    }

    val ready = generated
    if (ready == null) {
        DealingBoard(puzzle, onBack)
    } else {
        PlayBoard(puzzle, difficulty, day, ready, onSolved, onAgain, onBack)
    }
}

@Composable
private fun DealingBoard(puzzle: PuzzleType, onBack: () -> Unit) {
    val scheme = MaterialTheme.colorScheme
    Column(Modifier.fillMaxSize().background(scheme.background)) {
        Row(
            Modifier.fillMaxWidth().padding(start = 8.dp, end = 8.dp, top = 48.dp),
            verticalAlignment = Alignment.CenterVertically,
        ) {
            IconCircle(Icons.AutoMirrored.Filled.ArrowBack, "Back", onBack)
        }
        Box(Modifier.weight(1f), contentAlignment = Alignment.Center) {
            Text(
                "Setting out ${puzzle.displayName}...",
                style = MaterialTheme.typography.bodyMedium,
                color = scheme.onSurfaceVariant,
            )
        }
    }
}

@Composable
private fun PlayBoard(
    puzzle: PuzzleType,
    difficulty: Difficulty,
    day: LocalDate?,
    initial: PuzzleState,
    onSolved: (seconds: Int, hints: Int) -> Unit,
    onAgain: () -> Unit,
    onBack: () -> Unit,
) {
    val scheme = MaterialTheme.colorScheme

    var state by remember(initial) { mutableStateOf(initial) }
    var history by remember(initial) { mutableStateOf(listOf<PuzzleState>()) }
    var hints by remember(initial) { mutableIntStateOf(0) }
    var seconds by remember(initial) { mutableIntStateOf(0) }
    var showRules by remember { mutableStateOf(false) }
    var recorded by remember(initial) { mutableStateOf(false) }

    LaunchedEffect(initial) {
        while (true) {
            delay(1000)
            if (!state.solved) seconds++
        }
    }

    LaunchedEffect(state.solved) {
        if (state.solved && !recorded) {
            recorded = true
            onSolved(seconds, hints)
        }
    }

    fun push(next: PuzzleState) {
        history = history + state
        state = next
    }

    Column(Modifier.fillMaxSize().background(scheme.background)) {
        Row(
            Modifier.fillMaxWidth().padding(start = 8.dp, end = 8.dp, top = 48.dp, bottom = 6.dp),
            verticalAlignment = Alignment.CenterVertically,
        ) {
            IconCircle(Icons.AutoMirrored.Filled.ArrowBack, "Back", onBack)
            Column(Modifier.weight(1f), horizontalAlignment = Alignment.CenterHorizontally) {
                Text(
                    puzzle.displayName,
                    style = MaterialTheme.typography.titleLarge,
                    color = scheme.onBackground,
                )
                Text(
                    buildString {
                        append(difficulty.label)
                        append(" · ")
                        append(day?.format(PlayDate) ?: "Practice")
                    },
                    style = MaterialTheme.typography.labelLarge,
                    color = scheme.onSurfaceVariant,
                )
            }
            IconCircle(Icons.AutoMirrored.Filled.HelpOutline, "How to play") { showRules = true }
        }

        Text(
            text = "%d:%02d".format(seconds / 60, seconds % 60),
            style = MaterialTheme.typography.titleMedium,
            color = scheme.onSurfaceVariant,
            modifier = Modifier.fillMaxWidth().padding(bottom = 4.dp),
            textAlign = androidx.compose.ui.text.style.TextAlign.Center,
        )

        Box(Modifier.weight(1f), contentAlignment = Alignment.Center) {
            puzzle.Board(
                state = state,
                onState = { next -> push(next) },
                interactive = !state.solved,
            )
        }

        if (state.solved) {
            SolvedBar(
                seconds = seconds,
                hints = hints,
                accent = Color(puzzle.accent),
                onAgain = onAgain,
                onBack = onBack,
            )
        } else {
            Row(
                Modifier.fillMaxWidth().padding(horizontal = 18.dp, vertical = 22.dp),
                horizontalArrangement = Arrangement.spacedBy(12.dp),
            ) {
                ToolButton(Icons.AutoMirrored.Filled.Undo, "Undo", Modifier.weight(1f)) {
                    history.lastOrNull()?.let {
                        state = it
                        history = history.dropLast(1)
                    }
                }
                ToolButton(Icons.Default.Refresh, "Restart", Modifier.weight(1f)) {
                    history = emptyList()
                    state = initial
                }
                ToolButton(Icons.Default.AutoAwesome, "Hint", Modifier.weight(1f)) {
                    puzzle.hint(state)?.let {
                        hints++
                        push(it)
                    }
                }
            }
        }
    }

    if (showRules) {
        AlertDialog(
            onDismissRequest = { showRules = false },
            confirmButton = {
                TextButton(onClick = { showRules = false }) { Text("Got it") }
            },
            title = { Text("How to play ${puzzle.displayName}") },
            text = {
                Column(Modifier.verticalScroll(rememberScrollState())) {
                    puzzle.rules.forEach { rule ->
                        Text("•  $rule", style = MaterialTheme.typography.bodyMedium)
                        Spacer(Modifier.height(8.dp))
                    }
                }
            },
        )
    }
}

@Composable
private fun SolvedBar(
    seconds: Int,
    hints: Int,
    accent: Color,
    onAgain: () -> Unit,
    onBack: () -> Unit,
) {
    val scheme = MaterialTheme.colorScheme
    Column(
        Modifier
            .fillMaxWidth()
            .padding(18.dp)
            .clip(RoundedCornerShape(20.dp))
            .background(accent.copy(alpha = 0.18f))
            .padding(18.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
    ) {
        Text("Solved", style = MaterialTheme.typography.titleLarge, color = accent)
        Text(
            buildString {
                append("%d:%02d".format(seconds / 60, seconds % 60))
                if (hints > 0) append("  ·  $hints hint${if (hints == 1) "" else "s"}")
            },
            style = MaterialTheme.typography.bodyMedium,
            color = scheme.onSurface,
        )
        Spacer(Modifier.height(14.dp))
        Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
            TextButton(onClick = onAgain) { Text("Another") }
            TextButton(onClick = onBack) { Text("Done") }
        }
    }
}

@Composable
private fun IconCircle(icon: ImageVector, label: String, onClick: () -> Unit) {
    val scheme = MaterialTheme.colorScheme
    Box(
        Modifier.size(44.dp).clip(CircleShape).clickable(onClick = onClick),
        contentAlignment = Alignment.Center,
    ) {
        Icon(icon, label, tint = scheme.onSurfaceVariant)
    }
}

@Composable
private fun ToolButton(icon: ImageVector, label: String, modifier: Modifier, onClick: () -> Unit) {
    val scheme = MaterialTheme.colorScheme
    Column(
        modifier
            .clip(RoundedCornerShape(16.dp))
            .background(scheme.surface)
            .clickable(onClick = onClick)
            .padding(vertical = 13.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
    ) {
        Icon(icon, label, tint = scheme.onSurfaceVariant, modifier = Modifier.size(22.dp))
        Spacer(Modifier.height(4.dp))
        Text(label, style = MaterialTheme.typography.labelLarge, color = scheme.onSurfaceVariant)
    }
}
