package com.joebywan.daybook.puzzles

import androidx.compose.animation.core.RepeatMode
import androidx.compose.animation.core.animateFloat
import androidx.compose.animation.core.infiniteRepeatable
import androidx.compose.animation.core.rememberInfiniteTransition
import androidx.compose.animation.core.tween
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.gestures.detectDragGestures
import androidx.compose.foundation.gestures.detectTapGestures
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.BoxWithConstraints
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.State
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableFloatStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.CornerRadius
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.graphics.luminance
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.joebywan.daybook.core.BoardHighlight
import com.joebywan.daybook.core.Deduction
import com.joebywan.daybook.core.Difficulty
import com.joebywan.daybook.core.LocalBoardHighlight
import com.joebywan.daybook.core.PuzzleType
import com.joebywan.daybook.core.Rng
import com.joebywan.daybook.core.TutorialFrame
import kotlinx.serialization.Serializable

/** An axis-aligned block of cells, inclusive on both corners. */
@Serializable
data class Block(val r0: Int, val c0: Int, val r1: Int, val c1: Int) {
    val area: Int get() = (r1 - r0 + 1) * (c1 - c0 + 1)
    fun contains(r: Int, c: Int) = r in r0..r1 && c in c0..c1
    fun overlaps(other: Block) =
        r0 <= other.r1 && other.r0 <= r1 && c0 <= other.c1 && other.c0 <= c1
}

@Serializable
data class ShikakuState(
    val width: Int,
    val height: Int,
    val clues: List<Int?>,
    val blocks: List<Block>,
    val solution: List<Block>,
    override val moves: Int = 0,
) : PuzzleState {

    override val solved: Boolean get() = blocks.toSet() == solution.toSet()

    /** Adds a block, evicting anything it overlaps. Rejects blocks that hold other than one clue. */
    fun place(block: Block): ShikakuState {
        val cluesInside = (block.r0..block.r1).sumOf { r ->
            (block.c0..block.c1).count { c -> clues[r * width + c] != null }
        }
        val kept = blocks.filterNot { it.overlaps(block) }
        // A block with no clue just clears the area; a block with two or more is never legal.
        val next = if (cluesInside == 1) kept + block else kept
        return copy(blocks = next, moves = moves + 1)
    }

    fun blockAt(r: Int, c: Int): Block? = blocks.firstOrNull { it.contains(r, c) }
}

/**
 * Shikaku — cut the grid into rectangles, one number each, the number being the area.
 *
 * Generated by recursively slicing the grid, which guarantees a perfect tiling exists; the slicing
 * is then re-rolled until the clue placement admits only that one tiling.
 */
object Shikaku : PuzzleType {

    override val id = "shikaku"
    override val displayName = "Shikaku"
    override val tagline = "Cut the grid into numbered rectangles"
    override val accent = 0xFFE0B23C
    override val rules = listOf(
        "Divide the whole grid into rectangles.",
        "Every rectangle must contain exactly one number.",
        "That number is the rectangle's area in squares.",
        "Drag from one corner to another to draw a rectangle. Tap a rectangle to remove it.",
    )

    private fun shape(difficulty: Difficulty) = when (difficulty) {
        Difficulty.STANDARD -> Triple(6, 7, 6)
        Difficulty.HARD -> Triple(8, 9, 8)
        Difficulty.EXPERT -> Triple(9, 11, 10)
    }

    override fun generate(seed: Long, difficulty: Difficulty): PuzzleState {
        val (w, h, maxArea) = shape(difficulty)

        repeat(ATTEMPTS) { attempt ->
            val rng = Rng(seed + attempt)
            val blocks = slice(rng, Block(0, 0, h - 1, w - 1), maxArea)
            val clues = MutableList<Int?>(w * h) { null }
            blocks.forEach { block ->
                val r = rng.nextInt(block.r0, block.r1)
                val c = rng.nextInt(block.c0, block.c1)
                clues[r * w + c] = block.area
            }
            if (countTilings(w, h, clues) == 1) {
                return ShikakuState(w, h, clues.toList(), emptyList(), blocks)
            }
        }
        return fallbackBoard(seed, difficulty)
    }

    /**
     * How many slicings are tried before [generate] gives up and takes [fallbackBoard].
     *
     * Raised from 300 when clues of 1 were banned, and raised because measurement said so rather
     * than for comfort. A 1 is the most forcing clue there is — it fixes its own square and no
     * other — so dropping it makes uniqueness materially harder to hit: mean attempts went from
     * 8/20/18 per board to 11/35/29, and the tail went with it. At 300 a sweep of 4000 Hard seeds
     * already exhausted the budget once, which is a real board on a real date, not a rounding
     * error. At 2000, a wider sweep of 20000 seeds a tier never fell back at all, and its worst
     * seed took 355 attempts and 20 ms — so the budget sits about six times past the worst case
     * seen, and still two orders of magnitude inside the generator time limit.
     */
    private const val ATTEMPTS = 2000

    /**
     * The degenerate board taken when no re-roll produces a unique one: a clue in every
     * rectangle's own corner, which is trivially unique.
     *
     * Kept as a named function, and visible to tests, because it is unreachable in practice and an
     * unreachable path is exactly where a rule quietly stops holding. Kings, LITS and Mosaic have
     * each shipped a fallback that broke a guarantee the main path kept. It draws its rectangles
     * from the same [slice], so the no-clue-of-1 rule holds here structurally rather than by being
     * re-asserted, but a test still pins it.
     */
    internal fun fallbackBoard(seed: Long, difficulty: Difficulty): ShikakuState {
        val (w, h, maxArea) = shape(difficulty)
        val rng = Rng(seed)
        val blocks = slice(rng, Block(0, 0, h - 1, w - 1), maxArea)
        val clues = MutableList<Int?>(w * h) { null }
        blocks.forEach { clues[it.r0 * w + it.c0] = it.area }
        return ShikakuState(w, h, clues.toList(), emptyList(), blocks)
    }

    /**
     * The smallest rectangle the slicer is allowed to leave behind, and so the smallest clue any
     * board can carry.
     *
     * A clue of 1 names the square it is printed on, so it is answered by seeing it rather than by
     * working anything out, and it is the one rectangle a player cannot draw cleanly: a 1x1 drag is
     * the degenerate drag, indistinguishable from a slipped tap. Every clue is the area of the
     * block it came from, so refusing to *cut* a 1 is what keeps 1 off the board — there is no
     * separate check anywhere downstream, and no generate-then-reject loop to get the rate wrong.
     */
    private const val MIN_AREA = 2

    /**
     * Recursively halves a block until every piece is small enough to make a sensible clue.
     *
     * A cut is legal only when both halves clear [MIN_AREA]. Where the block is at least
     * [MIN_AREA] cells across the cut, every offset already clears it, because each half keeps a
     * whole row or column; it is only the strip one cell wide that measures its halves in single
     * cells, and there the block needs `2 * MIN_AREA` of length before any cut exists at all. A
     * block with no legal cut in either direction is returned whole, oversized or not — which
     * cannot happen for the grid sizes and areas in [shape], since anything over `maxArea` is
     * already longer than a strip needs to be splittable.
     */
    private fun slice(rng: Rng, block: Block, maxArea: Int): List<Block> {
        val rows = block.r1 - block.r0 + 1
        val cols = block.c1 - block.c0 + 1
        val rowInset = if (cols >= MIN_AREA) 0 else MIN_AREA - 1
        val colInset = if (rows >= MIN_AREA) 0 else MIN_AREA - 1
        val firstRowCut = block.r0 + rowInset
        val lastRowCut = block.r1 - 1 - rowInset
        val firstColCut = block.c0 + colInset
        val lastColCut = block.c1 - 1 - colInset
        val canSplitRows = firstRowCut <= lastRowCut
        val canSplitCols = firstColCut <= lastColCut

        val mustSplit = block.area > maxArea
        val wantSplit = rng.nextInt(100) < 55
        if ((!mustSplit && !wantSplit) || (!canSplitRows && !canSplitCols)) return listOf(block)

        val splitRows = when {
            !canSplitCols -> true
            !canSplitRows -> false
            else -> rows > cols || (rows == cols && rng.nextBoolean())
        }
        return if (splitRows) {
            val cut = rng.nextInt(firstRowCut, lastRowCut)
            slice(rng, block.copy(r1 = cut), maxArea) +
                slice(rng, block.copy(r0 = cut + 1), maxArea)
        } else {
            val cut = rng.nextInt(firstColCut, lastColCut)
            slice(rng, block.copy(c1 = cut), maxArea) +
                slice(rng, block.copy(c0 = cut + 1), maxArea)
        }
    }

    // ---- solver -------------------------------------------------------------------------------

    /** Counts perfect tilings consistent with the clues, stopping at two. */
    private fun countTilings(w: Int, h: Int, clues: List<Int?>): Int {
        val clueCells = clues.indices.filter { clues[it] != null }
        val candidates = clueCells.map { cell ->
            val cr = cell / w
            val cc = cell % w
            val area = clues[cell]!!
            buildList {
                for (height in 1..area) {
                    if (area % height != 0) continue
                    val width = area / height
                    for (r0 in maxOf(0, cr - height + 1)..cr) {
                        for (c0 in maxOf(0, cc - width + 1)..cc) {
                            val r1 = r0 + height - 1
                            val c1 = c0 + width - 1
                            if (r1 >= h || c1 >= w) continue
                            val block = Block(r0, c0, r1, c1)
                            // A rectangle may never swallow a second clue.
                            val clueCount = (r0..r1).sumOf { r ->
                                (c0..c1).count { c -> clues[r * w + c] != null }
                            }
                            if (clueCount == 1) add(block)
                        }
                    }
                }
            }
        }

        val owner = IntArray(w * h) { -1 }
        var found = 0

        fun fits(block: Block): Boolean {
            for (r in block.r0..block.r1) for (c in block.c0..block.c1) {
                if (owner[r * w + c] != -1) return false
            }
            return true
        }

        fun mark(block: Block, value: Int) {
            for (r in block.r0..block.r1) for (c in block.c0..block.c1) owner[r * w + c] = value
        }

        fun place(placed: Int) {
            if (found >= 2) return
            if (placed == clueCells.size) {
                found++
                return
            }
            // Most-constrained clue first: the fewest still-fitting rectangles.
            var bestClue = -1
            var bestOptions: List<Block>? = null
            for (k in clueCells.indices) {
                if (owner[clueCells[k]] != -1) continue
                val options = candidates[k].filter { fits(it) }
                if (options.isEmpty()) return
                if (bestOptions == null || options.size < bestOptions.size) {
                    bestClue = k
                    bestOptions = options
                    if (options.size == 1) break
                }
            }
            val options = bestOptions ?: return
            for (block in options) {
                if (!fits(block)) continue
                mark(block, bestClue)
                place(placed + 1)
                mark(block, -1)
                if (found >= 2) return
            }
        }

        place(0)
        return found
    }

    // ---- play ---------------------------------------------------------------------------------

    override fun hint(state: PuzzleState): PuzzleState? {
        val s = state as ShikakuState
        val missing = s.solution.firstOrNull { it !in s.blocks } ?: return null
        return s.place(missing)
    }

    // ---- walkthrough --------------------------------------------------------------------------

    /**
     * The walkthrough's board, 5x5:
     * ```
     * . 4 . 6 .      A A B B B
     * . . . . .      A A B B B
     * . . . 6 .      C D D E E
     * 3 . . . .      C D D E E
     * . . 6 . .      C D D E E
     * ```
     * Found by searching small boards for one whose hint walk runs the techniques in teaching order:
     * the top 6 fits only one way, then the 4 and the 3 are each the only number reaching a square,
     * then the middle 6's squares leave the bottom 6 one rectangle, and the last 6 fits. The frames
     * follow that walk; ShikakuTeachingTest proves the answer is unique and the moves are the hints'.
     */
    internal val TUTORIAL_CLUES = listOf<Int?>(
        null, 4, null, 6, null,
        null, null, null, null, null,
        null, null, null, 6, null,
        3, null, null, null, null,
        null, null, 6, null, null,
    )
    private const val TUTORIAL_SIZE = 5
    internal val TUTORIAL_TOP_SIX = Block(0, 2, 1, 4)
    internal val TUTORIAL_FOUR = Block(0, 0, 1, 1)
    internal val TUTORIAL_THREE = Block(2, 0, 4, 0)
    internal val TUTORIAL_LOW_SIX = Block(2, 1, 4, 2)
    internal val TUTORIAL_MID_SIX = Block(2, 3, 4, 4)
    internal val TUTORIAL_SOLUTION = listOf(TUTORIAL_TOP_SIX, TUTORIAL_FOUR, TUTORIAL_THREE, TUTORIAL_LOW_SIX, TUTORIAL_MID_SIX)

    /** The right size for the 4, and wrong: it leaves the corner square nothing can reach. */
    internal val TUTORIAL_WRONG_FOUR = Block(0, 1, 3, 1)

    private fun tutorialBoard(vararg blocks: Block) =
        ShikakuState(TUTORIAL_SIZE, TUTORIAL_SIZE, TUTORIAL_CLUES, blocks.toList(), TUTORIAL_SOLUTION)

    private fun cellsOf(b: Block) = (b.r0..b.r1).flatMap { r -> (b.c0..b.c1).map { c -> r * TUTORIAL_SIZE + c } }.toSet()

    /**
     * Accepts a board holding exactly [blocks] and nothing else. Strict on purpose: each frame's board
     * is written for the one before it.
     */
    private fun only(vararg blocks: Block): (PuzzleState) -> Boolean = { next ->
        next is ShikakuState && next.blocks.toSet() == blocks.toSet()
    }

    override val tutorial: List<TutorialFrame> by lazy {
        val top = TUTORIAL_TOP_SIX
        val four = TUTORIAL_FOUR
        val three = TUTORIAL_THREE
        val low = TUTORIAL_LOW_SIX
        listOf(
            TutorialFrame(
                state = tutorialBoard(*TUTORIAL_SOLUTION.toTypedArray()),
                caption = "Split the grid into rectangles. Each holds exactly one number, and that number " +
                    "is its area: this 6 covers six squares.",
                highlight = BoardHighlight(strong = cellsOf(top)),
            ),
            TutorialFrame(
                state = tutorialBoard(),
                caption = "This 6 needs six squares, and any other shape would run off the grid or take " +
                    "in another number. Drag from one corner to the opposite corner to draw it.",
                highlight = BoardHighlight(strong = cellsOf(top), soft = setOf(1, 13)),
                accepts = only(top),
                retry = "Drag from one glowing corner to the opposite one.",
                done = "Drawn.",
            ),
            TutorialFrame(
                state = tutorialBoard(top, TUTORIAL_WRONG_FOUR),
                caption = "This 4 is the right size, but then no number could reach the corner square, and " +
                    "every square needs one. Tap the rectangle to remove it.",
                highlight = BoardHighlight(strong = cellsOf(TUTORIAL_WRONG_FOUR), soft = setOf(0), warning = true),
                accepts = only(top),
                retry = "Tap the glowing rectangle once.",
                done = "Removed. A tap takes any rectangle away.",
            ),
            TutorialFrame(
                state = tutorialBoard(top),
                caption = "Only the 4 can reach the glowing corner, and just one of its rectangles covers " +
                    "it. Draw that one.",
                highlight = BoardHighlight(strong = setOf(0), soft = setOf(1)),
                accepts = only(top, four),
                retry = "Draw the 4's rectangle over the glowing corner.",
                done = "Drawn.",
            ),
            TutorialFrame(
                state = tutorialBoard(top, four),
                caption = "The same goes for the glowing square: only the 3 can reach it now. Draw the 3.",
                highlight = BoardHighlight(strong = setOf(10), soft = setOf(15)),
                accepts = only(top, four, three),
                retry = "Draw the 3's rectangle over the glowing square.",
                done = "Drawn.",
            ),
            TutorialFrame(
                state = tutorialBoard(top, four, three),
                caption = "Every rectangle this 6 can make covers the square below it, so the other 6 " +
                    "can't use that square. That leaves the other 6 one rectangle. Draw it.",
                highlight = BoardHighlight(strong = setOf(13, 18), soft = setOf(22)),
                accepts = only(top, four, three, low),
                retry = "Draw the bottom 6's rectangle, clear of the glowing squares.",
                done = "Drawn.",
            ),
            TutorialFrame(
                state = tutorialBoard(top, four, three, low),
                caption = "Your turn: finish the grid. Stuck? Hint shows you why.",
                freePlay = true,
                done = "Solved. That's all there is to it.",
            ),
        )
    }

    // ---- teaching -----------------------------------------------------------------------------

    /**
     * A mistake to take back or a step to reason out — see [ShikakuTeacher]. Replaces [hint] on the
     * play screen, which drew a rectangle straight out of [ShikakuState.solution] and taught nothing.
     */
    override fun teach(state: PuzzleState): Deduction? {
        val s = state as ShikakuState
        val step = ShikakuTeacher.teach(s) ?: return null
        return Deduction(
            technique = step.technique,
            nudge = step.nudge,
            explanation = step.explanation,
            focus = step.focus,
            cited = step.cited,
            targets = step.targets,
            mistake = step.technique == ShikakuTeacher.MISTAKE,
            fallback = step.technique == ShikakuTeacher.FALLBACK,
            applyTo = { now -> applyStep(now as ShikakuState, step) },
            reachedBy = { now ->
                val t = now as ShikakuState
                (step.place == null || step.place in t.blocks) && (step.remove == null || step.remove !in t.blocks)
            },
        )
    }

    /** "Show me": the step, made on the board as it is now. One state, so one undo entry. */
    private fun applyStep(s: ShikakuState, step: ShikakuTeacher.Step): ShikakuState {
        var next = s
        step.remove?.let { if (it in next.blocks) next = next.copy(blocks = next.blocks - it, moves = next.moves + 1) }
        step.place?.let { if (it !in next.blocks) next = next.place(it) }
        return next
    }

    // ---- home-grid motif ----------------------------------------------------------------------

    /**
     * A hand-picked 3x3 grid cut three ways. Written out rather than generated so the tile looks
     * the same on every device and every day.
     *
     * Three rectangles of three different shapes — a row, a square and a column — because two
     * would read as a split square and four at this size would read as a grid of cells. Their
     * top-left corners land on three different slots of [hue], so no two share a colour.
     */
    private val PREVIEW_BLOCKS = listOf(
        Block(0, 0, 0, 2),
        Block(1, 0, 2, 1),
        Block(1, 2, 2, 2),
    )

    /** One clue per rectangle, its area, sat where it sits on a real board: inside, off-centre. */
    private val PREVIEW_CLUES = listOf<Int?>(
        null, 3, null,
        4, null, 2,
        null, null, null,
    )

    /**
     * A grid already cut up, rather than the blank grid with clues a real puzzle starts from. The
     * tile has to say what the puzzle *is*, and the answer — coloured rectangles, one number each
     * — is legible at 80dp in a way that scattered numbers on grey would not be.
     */
    @Composable
    override fun Preview(modifier: Modifier) {
        val scheme = MaterialTheme.colorScheme
        val dark = scheme.background.luminance() < 0.5f
        BoxWithConstraints(modifier) {
            // Sized from both constraints, like Mosaic's board: a tile that is ever handed a
            // shorter box than it is wide should shrink rather than draw its bottom row outside.
            val cell = minOf(maxWidth, maxHeight) / 3
            for (r in 0 until 3) {
                for (c in 0 until 3) {
                    val owner = PREVIEW_BLOCKS.first { it.contains(r, c) }
                    Box(
                        Modifier
                            .padding(start = cell * c, top = cell * r)
                            .size(cell)
                            .padding(0.7.dp)
                            .clip(RoundedCornerShape(3.dp))
                            .background(owner.fill(dark)),
                        contentAlignment = Alignment.Center,
                    ) {
                        PREVIEW_CLUES[r * 3 + c]?.let { clue ->
                            Text(
                                clue.toString(),
                                fontSize = (cell.value * 0.46f).sp,
                                fontWeight = FontWeight.Bold,
                                color = scheme.onSurface,
                            )
                        }
                    }
                }
            }
            PREVIEW_BLOCKS.forEach { block ->
                Box(
                    Modifier
                        .padding(start = cell * block.c0, top = cell * block.r0)
                        .width(cell * (block.c1 - block.c0 + 1))
                        .height(cell * (block.r1 - block.r0 + 1))
                        .padding(1.dp)
                        .border(2.dp, block.edge(dark), RoundedCornerShape(4.dp))
                )
            }
        }
    }

    @Composable
    override fun Board(state: PuzzleState, onState: (PuzzleState) -> Unit, interactive: Boolean) {
        val s = state as ShikakuState
        val scheme = MaterialTheme.colorScheme
        val dark = scheme.background.luminance() < 0.5f
        val highlight = LocalBoardHighlight.current
        val glow = if (highlight.warning) scheme.error else scheme.onBackground
        // Breathes, as the other teaching boards' do, so a glowing square is findable at a glance on
        // a 9x11 board. Only runs while something glows, and is read in the draw phase.
        val pulse: State<Float> = if (highlight.strong.isEmpty()) {
            remember { mutableFloatStateOf(1f) }
        } else {
            rememberInfiniteTransition(label = "hint").animateFloat(
                initialValue = 0.45f,
                targetValue = 1f,
                animationSpec = infiniteRepeatable(tween(700), RepeatMode.Reverse),
                label = "hint-pulse",
            )
        }
        var dragFrom by remember(s.solution) { mutableStateOf<Pair<Int, Int>?>(null) }
        var dragTo by remember(s.solution) { mutableStateOf<Pair<Int, Int>?>(null) }

        // Sized from both axes (CLAUDE.md), so a tall board or a short screen never runs it under
        // the hint slot.
        BoxWithConstraints(Modifier.fillMaxWidth().padding(14.dp), contentAlignment = Alignment.Center) {
            val cell = if (constraints.hasBoundedHeight) minOf(maxWidth / s.width, maxHeight / s.height) else maxWidth / s.width
            val cellPx = with(LocalDensity.current) { cell.toPx() }

            fun cellAt(offset: Offset): Pair<Int, Int> =
                (offset.y / cellPx).toInt().coerceIn(0, s.height - 1) to
                    (offset.x / cellPx).toInt().coerceIn(0, s.width - 1)

            val preview = dragFrom?.let { from ->
                dragTo?.let { to ->
                    Block(
                        minOf(from.first, to.first), minOf(from.second, to.second),
                        maxOf(from.first, to.first), maxOf(from.second, to.second),
                    )
                }
            }

            Box(
                Modifier
                    .width(cell * s.width)
                    .height(cell * s.height)
                    .pointerInput(s, interactive) {
                        if (!interactive) return@pointerInput
                        detectTapGestures { offset ->
                            val (r, c) = cellAt(offset)
                            s.blockAt(r, c)?.let { existing ->
                                onState(s.copy(blocks = s.blocks - existing, moves = s.moves + 1))
                            }
                        }
                    }
                    .pointerInput(s, interactive) {
                        if (!interactive) return@pointerInput
                        // The overload that hands over the touch-down itself. The plain one reports
                        // where the finger crossed the touch slop, which on the web is wide enough
                        // to start a rectangle a square away from the corner the player pressed.
                        detectDragGestures(
                            orientationLock = null,
                            onDragStart = { down, _, _ ->
                                dragFrom = cellAt(down.position)
                                dragTo = dragFrom
                            },
                            onDrag = { change, _ ->
                                dragTo = cellAt(change.position)
                            },
                            onDragEnd = { _ ->
                                val from = dragFrom
                                val to = dragTo
                                if (from != null && to != null) {
                                    onState(
                                        s.place(
                                            Block(
                                                minOf(from.first, to.first),
                                                minOf(from.second, to.second),
                                                maxOf(from.first, to.first),
                                                maxOf(from.second, to.second),
                                            )
                                        )
                                    )
                                }
                                dragFrom = null
                                dragTo = null
                            },
                            onDragCancel = {
                                dragFrom = null
                                dragTo = null
                            },
                        )
                    }
            ) {
                // Squares.
                for (r in 0 until s.height) {
                    for (c in 0 until s.width) {
                        val i = r * s.width + c
                        val owner = s.blockAt(r, c)
                        Box(
                            Modifier
                                .padding(start = cell * c, top = cell * r)
                                .size(cell)
                                .padding(0.7.dp)
                                .clip(RoundedCornerShape(3.dp))
                                .background(owner?.fill(dark) ?: scheme.surfaceVariant),
                            contentAlignment = Alignment.Center,
                        ) {
                            s.clues[i]?.let { clue ->
                                Text(
                                    clue.toString(),
                                    fontSize = (cell.value * 0.46f).sp,
                                    fontWeight = FontWeight.Bold,
                                    color = scheme.onSurface,
                                )
                            }
                        }
                    }
                }

                // Each committed rectangle is outlined in its own hue, matching its fill.
                s.blocks.forEach { block ->
                    Box(
                        Modifier
                            .padding(start = cell * block.c0, top = cell * block.r0)
                            .width(cell * (block.c1 - block.c0 + 1))
                            .height(cell * (block.r1 - block.r0 + 1))
                            .padding(1.dp)
                            .border(2.dp, block.edge(dark), RoundedCornerShape(4.dp))
                    )
                }

                // What a hint names. Everything else steps back under a veil in the page colour, so
                // the named squares read without hunting; strong squares pulse, soft ones are quiet.
                if (!highlight.isEmpty) {
                    Canvas(Modifier.matchParentSize()) {
                        val strongW = 4.dp.toPx()
                        val softW = 1.5.dp.toPx()
                        val corner = CornerRadius(4.dp.toPx())
                        for (i in s.clues.indices) {
                            val strong = i in highlight.strong
                            val soft = !strong && i in highlight.soft
                            val topLeft = Offset((i % s.width) * cellPx, (i / s.width) * cellPx)
                            if (!strong && !soft) {
                                drawRect(scheme.background.copy(alpha = 0.62f), topLeft, Size(cellPx, cellPx))
                                continue
                            }
                            val w = if (strong) strongW else softW
                            if (strong) {
                                drawRoundRect(
                                    color = glow.copy(alpha = 0.16f * pulse.value),
                                    topLeft = topLeft,
                                    size = Size(cellPx, cellPx),
                                    cornerRadius = corner,
                                )
                            }
                            drawRoundRect(
                                color = if (strong) glow.copy(alpha = pulse.value) else glow.copy(alpha = 0.5f),
                                topLeft = Offset(topLeft.x + w / 2, topLeft.y + w / 2),
                                size = Size(cellPx - w, cellPx - w),
                                cornerRadius = corner,
                                style = Stroke(w),
                            )
                        }
                    }
                }

                // The drag is set apart on three counts at once — the theme's own green, a washed
                // fill and a heavier edge — so a rectangle under the finger can never be read as
                // one already placed.
                preview?.let { block ->
                    Box(
                        Modifier
                            .padding(start = cell * block.c0, top = cell * block.r0)
                            .width(cell * (block.c1 - block.c0 + 1))
                            .height(cell * (block.r1 - block.r0 + 1))
                            .padding(1.dp)
                            .clip(RoundedCornerShape(4.dp))
                            .background(scheme.primary.copy(alpha = 0.22f))
                            .border(3.dp, scheme.primary, RoundedCornerShape(4.dp))
                    )
                }
            }
        }
    }

    // ---- rectangle colours --------------------------------------------------------------------

    /**
     * Which of [HUES] a rectangle takes, keyed on its top-left corner.
     *
     * Keyed on the corner rather than on the rectangle's place in [ShikakuState.blocks], so that a
     * rectangle holds its colour while its neighbours are drawn and torn up around it. The weights
     * 1 and 3 over eight slots are chosen so two corners within three cells of one another can
     * never share a slot, which covers every way two rectangles can meet at the sizes this
     * generator produces.
     *
     * The wheel is rolled off zero so that the slots straddle the theme's green rather than one
     * landing on it, leaving the drag preview a hue of its own.
     */
    private fun Block.hue(): Float = (r0 + c0 * 3).mod(HUES) * (360f / HUES) + 2.5f

    /** Pale enough in either theme that the clue printed on top keeps its contrast. */
    private fun Block.fill(dark: Boolean): Color =
        if (dark) Color.hsl(hue(), 0.40f, 0.30f) else Color.hsl(hue(), 0.62f, 0.76f)

    /** The same hue pushed away from the fill, so the seam between two rectangles stays a line. */
    private fun Block.edge(dark: Boolean): Color =
        if (dark) Color.hsl(hue(), 0.55f, 0.64f) else Color.hsl(hue(), 0.55f, 0.38f)

    private const val HUES = 8
}
