package com.joebywan.daybook.puzzles

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.gestures.detectDragGestures
import androidx.compose.foundation.gestures.detectTapGestures
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.BoxWithConstraints
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.luminance
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.joebywan.daybook.core.Difficulty
import com.joebywan.daybook.core.PuzzleType
import com.joebywan.daybook.core.Rng
import kotlinx.serialization.Serializable

/** An axis-aligned block of cells, inclusive on both corners. */
@Serializable
data class Block(val r0: Int, val c0: Int, val r1: Int, val c1: Int) {
    val area: Int get() = (r1 - r0 + 1) * (c1 - c0 + 1)
    fun contains(r: Int, c: Int) = r in r0..r1 && c in c0..c1
    fun overlaps(other: Block) =
        r0 <= other.r1 && other.r0 <= r1 && c0 <= other.c1 && other.c0 <= c1
}

@Serializable
data class ShikakuState(
    val width: Int,
    val height: Int,
    val clues: List<Int?>,
    val blocks: List<Block>,
    val solution: List<Block>,
    override val moves: Int = 0,
) : PuzzleState {

    override val solved: Boolean get() = blocks.toSet() == solution.toSet()

    /** Adds a block, evicting anything it overlaps. Rejects blocks that hold other than one clue. */
    fun place(block: Block): ShikakuState {
        val cluesInside = (block.r0..block.r1).sumOf { r ->
            (block.c0..block.c1).count { c -> clues[r * width + c] != null }
        }
        val kept = blocks.filterNot { it.overlaps(block) }
        // A block with no clue just clears the area; a block with two or more is never legal.
        val next = if (cluesInside == 1) kept + block else kept
        return copy(blocks = next, moves = moves + 1)
    }

    fun blockAt(r: Int, c: Int): Block? = blocks.firstOrNull { it.contains(r, c) }
}

/**
 * Shikaku — cut the grid into rectangles, one number each, the number being the area.
 *
 * Generated by recursively slicing the grid, which guarantees a perfect tiling exists; the slicing
 * is then re-rolled until the clue placement admits only that one tiling.
 */
object Shikaku : PuzzleType {

    override val id = "shikaku"
    override val displayName = "Shikaku"
    override val tagline = "Cut the grid into numbered rectangles"
    override val accent = 0xFFE0B23C
    override val rules = listOf(
        "Divide the whole grid into rectangles.",
        "Every rectangle must contain exactly one number.",
        "That number is the rectangle's area in squares.",
        "Drag from one corner to another to draw a rectangle. Tap a rectangle to remove it.",
    )

    private fun shape(difficulty: Difficulty) = when (difficulty) {
        Difficulty.STANDARD -> Triple(6, 7, 6)
        Difficulty.HARD -> Triple(8, 9, 8)
        Difficulty.EXPERT -> Triple(9, 11, 10)
    }

    override fun generate(seed: Long, difficulty: Difficulty): PuzzleState {
        val (w, h, maxArea) = shape(difficulty)

        repeat(300) { attempt ->
            val rng = Rng(seed + attempt)
            val blocks = slice(rng, Block(0, 0, h - 1, w - 1), maxArea)
            val clues = MutableList<Int?>(w * h) { null }
            blocks.forEach { block ->
                val r = rng.nextInt(block.r0, block.r1)
                val c = rng.nextInt(block.c0, block.c1)
                clues[r * w + c] = block.area
            }
            if (countTilings(w, h, clues) == 1) {
                return ShikakuState(w, h, clues.toList(), emptyList(), blocks)
            }
        }

        // Fallback: a clue in every cell is trivially unique.
        val rng = Rng(seed)
        val blocks = slice(rng, Block(0, 0, h - 1, w - 1), maxArea)
        val clues = MutableList<Int?>(w * h) { null }
        blocks.forEach { clues[it.r0 * w + it.c0] = it.area }
        return ShikakuState(w, h, clues.toList(), emptyList(), blocks)
    }

    /** Recursively halves a block until every piece is small enough to make a sensible clue. */
    private fun slice(rng: Rng, block: Block, maxArea: Int): List<Block> {
        val rows = block.r1 - block.r0 + 1
        val cols = block.c1 - block.c0 + 1
        val canSplitRows = rows > 1
        val canSplitCols = cols > 1

        val mustSplit = block.area > maxArea
        val wantSplit = block.area > 2 && rng.nextInt(100) < 55
        if ((!mustSplit && !wantSplit) || (!canSplitRows && !canSplitCols)) return listOf(block)

        val splitRows = when {
            !canSplitCols -> true
            !canSplitRows -> false
            else -> rows > cols || (rows == cols && rng.nextBoolean())
        }
        return if (splitRows) {
            val cut = rng.nextInt(block.r0, block.r1 - 1)
            slice(rng, block.copy(r1 = cut), maxArea) +
                slice(rng, block.copy(r0 = cut + 1), maxArea)
        } else {
            val cut = rng.nextInt(block.c0, block.c1 - 1)
            slice(rng, block.copy(c1 = cut), maxArea) +
                slice(rng, block.copy(c0 = cut + 1), maxArea)
        }
    }

    // ---- solver -------------------------------------------------------------------------------

    /** Counts perfect tilings consistent with the clues, stopping at two. */
    private fun countTilings(w: Int, h: Int, clues: List<Int?>): Int {
        val clueCells = clues.indices.filter { clues[it] != null }
        val candidates = clueCells.map { cell ->
            val cr = cell / w
            val cc = cell % w
            val area = clues[cell]!!
            buildList {
                for (height in 1..area) {
                    if (area % height != 0) continue
                    val width = area / height
                    for (r0 in maxOf(0, cr - height + 1)..cr) {
                        for (c0 in maxOf(0, cc - width + 1)..cc) {
                            val r1 = r0 + height - 1
                            val c1 = c0 + width - 1
                            if (r1 >= h || c1 >= w) continue
                            val block = Block(r0, c0, r1, c1)
                            // A rectangle may never swallow a second clue.
                            val clueCount = (r0..r1).sumOf { r ->
                                (c0..c1).count { c -> clues[r * w + c] != null }
                            }
                            if (clueCount == 1) add(block)
                        }
                    }
                }
            }
        }

        val owner = IntArray(w * h) { -1 }
        var found = 0

        fun fits(block: Block): Boolean {
            for (r in block.r0..block.r1) for (c in block.c0..block.c1) {
                if (owner[r * w + c] != -1) return false
            }
            return true
        }

        fun mark(block: Block, value: Int) {
            for (r in block.r0..block.r1) for (c in block.c0..block.c1) owner[r * w + c] = value
        }

        fun place(placed: Int) {
            if (found >= 2) return
            if (placed == clueCells.size) {
                found++
                return
            }
            // Most-constrained clue first: the fewest still-fitting rectangles.
            var bestClue = -1
            var bestOptions: List<Block>? = null
            for (k in clueCells.indices) {
                if (owner[clueCells[k]] != -1) continue
                val options = candidates[k].filter { fits(it) }
                if (options.isEmpty()) return
                if (bestOptions == null || options.size < bestOptions.size) {
                    bestClue = k
                    bestOptions = options
                    if (options.size == 1) break
                }
            }
            val options = bestOptions ?: return
            for (block in options) {
                if (!fits(block)) continue
                mark(block, bestClue)
                place(placed + 1)
                mark(block, -1)
                if (found >= 2) return
            }
        }

        place(0)
        return found
    }

    // ---- play ---------------------------------------------------------------------------------

    override fun hint(state: PuzzleState): PuzzleState? {
        val s = state as ShikakuState
        val missing = s.solution.firstOrNull { it !in s.blocks } ?: return null
        return s.place(missing)
    }

    // ---- home-grid motif ----------------------------------------------------------------------

    /**
     * A hand-picked 3x3 grid cut three ways. Written out rather than generated so the tile looks
     * the same on every device and every day.
     *
     * Three rectangles of three different shapes — a row, a square and a column — because two
     * would read as a split square and four at this size would read as a grid of cells. Their
     * top-left corners land on three different slots of [hue], so no two share a colour.
     */
    private val PREVIEW_BLOCKS = listOf(
        Block(0, 0, 0, 2),
        Block(1, 0, 2, 1),
        Block(1, 2, 2, 2),
    )

    /** One clue per rectangle, its area, sat where it sits on a real board: inside, off-centre. */
    private val PREVIEW_CLUES = listOf<Int?>(
        null, 3, null,
        4, null, 2,
        null, null, null,
    )

    /**
     * A grid already cut up, rather than the blank grid with clues a real puzzle starts from. The
     * tile has to say what the puzzle *is*, and the answer — coloured rectangles, one number each
     * — is legible at 80dp in a way that scattered numbers on grey would not be.
     */
    @Composable
    override fun Preview(modifier: Modifier) {
        val scheme = MaterialTheme.colorScheme
        val dark = scheme.background.luminance() < 0.5f
        BoxWithConstraints(modifier) {
            // Sized from both constraints, like Mosaic's board: a tile that is ever handed a
            // shorter box than it is wide should shrink rather than draw its bottom row outside.
            val cell = minOf(maxWidth, maxHeight) / 3
            for (r in 0 until 3) {
                for (c in 0 until 3) {
                    val owner = PREVIEW_BLOCKS.first { it.contains(r, c) }
                    Box(
                        Modifier
                            .padding(start = cell * c, top = cell * r)
                            .size(cell)
                            .padding(0.7.dp)
                            .clip(RoundedCornerShape(3.dp))
                            .background(owner.fill(dark)),
                        contentAlignment = Alignment.Center,
                    ) {
                        PREVIEW_CLUES[r * 3 + c]?.let { clue ->
                            Text(
                                clue.toString(),
                                fontSize = (cell.value * 0.46f).sp,
                                fontWeight = FontWeight.Bold,
                                color = scheme.onSurface,
                            )
                        }
                    }
                }
            }
            PREVIEW_BLOCKS.forEach { block ->
                Box(
                    Modifier
                        .padding(start = cell * block.c0, top = cell * block.r0)
                        .width(cell * (block.c1 - block.c0 + 1))
                        .height(cell * (block.r1 - block.r0 + 1))
                        .padding(1.dp)
                        .border(2.dp, block.edge(dark), RoundedCornerShape(4.dp))
                )
            }
        }
    }

    @Composable
    override fun Board(state: PuzzleState, onState: (PuzzleState) -> Unit, interactive: Boolean) {
        val s = state as ShikakuState
        val scheme = MaterialTheme.colorScheme
        val dark = scheme.background.luminance() < 0.5f
        var dragFrom by remember(s.solution) { mutableStateOf<Pair<Int, Int>?>(null) }
        var dragTo by remember(s.solution) { mutableStateOf<Pair<Int, Int>?>(null) }

        BoxWithConstraints(Modifier.fillMaxWidth().padding(14.dp)) {
            val cell = maxWidth / s.width
            val cellPx = with(LocalDensity.current) { cell.toPx() }

            fun cellAt(offset: Offset): Pair<Int, Int> =
                (offset.y / cellPx).toInt().coerceIn(0, s.height - 1) to
                    (offset.x / cellPx).toInt().coerceIn(0, s.width - 1)

            val preview = dragFrom?.let { from ->
                dragTo?.let { to ->
                    Block(
                        minOf(from.first, to.first), minOf(from.second, to.second),
                        maxOf(from.first, to.first), maxOf(from.second, to.second),
                    )
                }
            }

            Box(
                Modifier
                    .width(cell * s.width)
                    .height(cell * s.height)
                    .pointerInput(s, interactive) {
                        if (!interactive) return@pointerInput
                        detectTapGestures { offset ->
                            val (r, c) = cellAt(offset)
                            s.blockAt(r, c)?.let { existing ->
                                onState(s.copy(blocks = s.blocks - existing, moves = s.moves + 1))
                            }
                        }
                    }
                    .pointerInput(s, interactive) {
                        if (!interactive) return@pointerInput
                        detectDragGestures(
                            onDragStart = { offset ->
                                dragFrom = cellAt(offset)
                                dragTo = dragFrom
                            },
                            onDrag = { change, _ ->
                                dragTo = cellAt(change.position)
                            },
                            onDragEnd = {
                                val from = dragFrom
                                val to = dragTo
                                if (from != null && to != null) {
                                    onState(
                                        s.place(
                                            Block(
                                                minOf(from.first, to.first),
                                                minOf(from.second, to.second),
                                                maxOf(from.first, to.first),
                                                maxOf(from.second, to.second),
                                            )
                                        )
                                    )
                                }
                                dragFrom = null
                                dragTo = null
                            },
                            onDragCancel = {
                                dragFrom = null
                                dragTo = null
                            },
                        )
                    }
            ) {
                // Squares.
                for (r in 0 until s.height) {
                    for (c in 0 until s.width) {
                        val i = r * s.width + c
                        val owner = s.blockAt(r, c)
                        Box(
                            Modifier
                                .padding(start = cell * c, top = cell * r)
                                .size(cell)
                                .padding(0.7.dp)
                                .clip(RoundedCornerShape(3.dp))
                                .background(owner?.fill(dark) ?: scheme.surfaceVariant),
                            contentAlignment = Alignment.Center,
                        ) {
                            s.clues[i]?.let { clue ->
                                Text(
                                    clue.toString(),
                                    fontSize = (cell.value * 0.46f).sp,
                                    fontWeight = FontWeight.Bold,
                                    color = scheme.onSurface,
                                )
                            }
                        }
                    }
                }

                // Each committed rectangle is outlined in its own hue, matching its fill.
                s.blocks.forEach { block ->
                    Box(
                        Modifier
                            .padding(start = cell * block.c0, top = cell * block.r0)
                            .width(cell * (block.c1 - block.c0 + 1))
                            .height(cell * (block.r1 - block.r0 + 1))
                            .padding(1.dp)
                            .border(2.dp, block.edge(dark), RoundedCornerShape(4.dp))
                    )
                }

                // The drag is set apart on three counts at once — the theme's own green, a washed
                // fill and a heavier edge — so a rectangle under the finger can never be read as
                // one already placed.
                preview?.let { block ->
                    Box(
                        Modifier
                            .padding(start = cell * block.c0, top = cell * block.r0)
                            .width(cell * (block.c1 - block.c0 + 1))
                            .height(cell * (block.r1 - block.r0 + 1))
                            .padding(1.dp)
                            .clip(RoundedCornerShape(4.dp))
                            .background(scheme.primary.copy(alpha = 0.22f))
                            .border(3.dp, scheme.primary, RoundedCornerShape(4.dp))
                    )
                }
            }
        }
    }

    // ---- rectangle colours --------------------------------------------------------------------

    /**
     * Which of [HUES] a rectangle takes, keyed on its top-left corner.
     *
     * Keyed on the corner rather than on the rectangle's place in [ShikakuState.blocks], so that a
     * rectangle holds its colour while its neighbours are drawn and torn up around it. The weights
     * 1 and 3 over eight slots are chosen so two corners within three cells of one another can
     * never share a slot, which covers every way two rectangles can meet at the sizes this
     * generator produces.
     *
     * The wheel is rolled off zero so that the slots straddle the theme's green rather than one
     * landing on it, leaving the drag preview a hue of its own.
     */
    private fun Block.hue(): Float = (r0 + c0 * 3).mod(HUES) * (360f / HUES) + 2.5f

    /** Pale enough in either theme that the clue printed on top keeps its contrast. */
    private fun Block.fill(dark: Boolean): Color =
        if (dark) Color.hsl(hue(), 0.40f, 0.30f) else Color.hsl(hue(), 0.62f, 0.76f)

    /** The same hue pushed away from the fill, so the seam between two rectangles stays a line. */
    private fun Block.edge(dark: Boolean): Color =
        if (dark) Color.hsl(hue(), 0.55f, 0.64f) else Color.hsl(hue(), 0.55f, 0.38f)

    private const val HUES = 8
}
